[package]
name = "simple-factory"
version = "0.1.0-dev"
edition = "2018"
description = "Pattern Simple Factory"
authors = ["Jeka <developer@gmail.com>"]
readme = "README.md"

[dependencies]
once_cell = "1.3"
lazy_static = "1.4"

